version: 1.4.0

environment:
  matrix:
    - job_name: Windows (MSVC)
      ARCH: x64
      COMPILER: VS2019
      QTDIR: C:\Qt\6.2\msvc2019_64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - job_name: Mac OSX (Clang)
      APPVEYOR_BUILD_WORKER_IMAGE: macOS-BigSur

matrix:
  fast_finish: true

platform:
  - x64
configuration:
  - Release
  
for:
  - # Windows
    matrix:
      only:
        - job_name: Windows (MSVC)

    before_build:
      - set SOURCEDIR=%cd%
      - call %QTDIR%\bin\qtenv2.bat
      - cd /D %SOURCEDIR%
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

    build_script:
      - mkdir .\build
      - cd .\build
      - cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=RELEASE ../
      - cmake --build .
      - call %QTDIR%\bin\windeployqt --release discord-music-presence.exe

    after_build:
      - xcopy /c "C:\OpenSSL-v111-Win64\bin\*.dll"
      - echo zipping %APPVEYOR_BUILD_VERSION%
      - 7z a discord-music-presence.zip discord-music-presence.exe *.dll ./imageformats/ ./platforms/ ./styles/ ./iconengines ./tls

    artifacts:
      - path: build/discord-music-presence.zip
        name: discord-music-presence.zip
        type: zip

    deploy:
      - provider: GitHub
        release: "Discord Music Presence v$(APPVEYOR_BUILD_VERSION)"
        description: "Discord Music Presence"
        tag: v$(APPVEYOR_BUILD_VERSION)
        auth_token:
          secure: jIbkiObOwXasiWeUpE0CEC5sJQcFpfFtjSSlg9DG40JnQrNDzXf/jC4VvIZFDRY/Od5pEL8jaHtAgxqjAOXb1EEF4wEVM/MpreIKHHiwe8/16NUAPtGV48FqGyTDP+0O # your encrypted token from GitHub
        artifact: discord-music-presence.zip # upload all NuGet packages to release assets
        draft: true
        prerelease: false
        on:
          APPVEYOR_REPO_TAG: true

  - # Mac
    matrix:
      only:
        - job_name: Mac OSX (Clang)
        
    build_script:
      - mkdir build
      - cd build
      - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE ../ -DQt6_DIR=$HOME/Qt/6.4.0/macos/lib/cmake/Qt6 -DQt6CoreTools_DIR=$HOME/Qt/6.4.0/macos/lib/cmake/Qt6CoreTools -DQt6GuiTools_DIR=$HOME/Qt/6.4.0/macos/lib/cmake/Qt6GuiTools -DQt6WidgetsTools_DIR=$HOME/Qt/6.4.0/macos/lib/cmake/Qt6WidgetsTools ..
      - cmake --build .
      - $HOME/Qt/6.4.0/macos/bin/macdeployqt discord-music-presence.app -dmg

    after_build:
      - echo $APPVEYOR_BUILD_FOLDER
      - ls
      - pwd

    artifacts:
      - path: build/discord-music-presence.dmg
        name: discord-music-presence.dmg
        type: file

    deploy:
      - provider: GitHub
        release: "Discord Music Presence v$(APPVEYOR_BUILD_VERSION)"
        description: "Discord Music Presence"
        tag: v$(APPVEYOR_BUILD_VERSION)
        auth_token:
          secure: jIbkiObOwXasiWeUpE0CEC5sJQcFpfFtjSSlg9DG40JnQrNDzXf/jC4VvIZFDRY/Od5pEL8jaHtAgxqjAOXb1EEF4wEVM/MpreIKHHiwe8/16NUAPtGV48FqGyTDP+0O # your encrypted token from GitHub
        artifact: discord-music-presence.dmg # upload all NuGet packages to release assets
        draft: true
        prerelease: false
        on:
          APPVEYOR_REPO_TAG: true
